#!/usr/bin/env bash
# this does the following:
#  it create a file /var/run/myscript.pid containing the script PID.
#  it displays "To infinity and beyond" indefinitely
#  it displays "I hate the kill command" upon receiving a SIGTERM
#  it displays "Y U no love me?!" upon receiving a SIGINT
#  it deletes the file /var/run/mycript.pid and terminates upon
#+ and receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
