#!/usr/bin/env bash
# Script to display "To infinity and beyond", react to SIGTERM with "I am invincible!!!"
trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
