#!/usr/bin/env bash
# this displays To infinity and beyond indefinitely
# and  a sleep 2 in between each iteration
# So I am invincible!!! when receiving a SIGTERM signal

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
