#!/usr/bin/env bash
# Display information about users from /etc/passwd

while IFS=":" read -r user _ uid gid desc home shell; do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $desc"
done </etc/passwd
