#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
n=0
while [ $n -lt 13 ]; do
    echo "Hour: $n"
    m=1
    while [ $m -lt 60 ]; do
        echo "$m"
        ((m++));
    done
    ((n++));
done
