#!/usr/bin/env bash
# this configures an Ubuntu server as follows:
#   -this one  localhost resolves to 127.0.0.2
#   - and here facebook.com resolves to 8.8.8.8

cp /etc/hosts new_hosts
sed -i s/^127.*/"127.0.0.2 localhost"/ new_hosts
echo "8.8.8.8 facebook.com" >> new_hosts
cp new_hosts /etc/hosts
